name: visionscan
description: "Scan Anything. Anywhere."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1
  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^5.7.0
  flutter_screenutil: ^5.5.3
  flutter_svg: ^2.0.16
  shared_preferences: ^2.5.3
  url_launcher: ^6.2.3
  smooth_page_indicator: ^1.2.1
  google_fonts: ^6.2.1
  mobile_scanner: ^7.0.1
  lottie: ^3.3.1
  pretty_qr_code: ^3.4.0
  flutter_native_contact_picker: ^0.0.10
  path_provider: ^2.1.5
  barcode_widget: ^2.0.4
  gallery_saver_plus: ^3.2.8
  flutter_doc_scanner: ^0.0.16
  file_saver: ^0.3.0
  syncfusion_flutter_pdfviewer: ^30.1.39
  syncfusion_flutter_core: ^30.1.39
  floor: ^1.4.2
  share_plus: ^11.0.0
  sqflite: ^2.4.2
  file_picker: ^10.2.0
  pdf_render: ^1.4.7
  flutter_reorderable_grid_view: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/vectors/
    - assets/animations/
    - assets/qr/
